IMPORT LIBRARY YANG DIBUTUHKAN

In [8]:
from __future__ import print_function

import IPython
print('IPython:', IPython.__version__)

import numpy
print('Numpy:', numpy.__version__)

import pandas
print('Pandas:', pandas.__version__)

import sklearn
print('Scikit-learn:', sklearn.__version__)

IPython: 7.34.0
Numpy: 2.0.2
Pandas: 2.2.2
Scikit-learn: 1.6.1


**LOAD DATA IRIS** bawaan asli (built-in) dari modul sklearn.datasets di dalam library scikit-learn

In [11]:
from sklearn.datasets import load_iris
iris = load_iris()

MENAMPILKAN TIPE DATA NUMPY ARRAY DAN PANDAS DATAFRAME

In [12]:
X, y = iris.data, iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


MEMBUAT PIPELINE UNTUK NUMPY DAN PANDAS

In [18]:
import pandas as pd

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target #target

df.head()

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

pipe_numpy = make_pipeline(StandardScaler(), LinearSVC())
pipe_pandas = make_pipeline(StandardScaler(), LinearSVC())

MELAKUKAN SPLITTING

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,  random_state=46)

df_train, df_test = train_test_split(df, test_size=0.2, random_state=46)

MELAKUKAN TRAINING

In [23]:
#Numpy dilakukan scaling dan model -> kunci untuk training adalah nama pipeline.fit
pipe_numpy.fit(X_train, y_train)
y_pred = pipe_numpy.predict(X_test)

#Menampilkan hasil evaluasi hasil dari model yang sudah dibuat
print(classification_report(y_test, y_pred))

#Pandas
X_train_df, y_train_df = df_train.drop('target', axis=1), df_train['target']
X_test_df, y_test_df = df_test.drop('target', axis=1), df_test['target']
pipe_pandas.fit(X_train_df, y_train_df)
y_pred_df = pipe_pandas.predict(X_test_df)

print("Hasil evaluasi model pandas")
print(classification_report(y_test_df, y_pred_df))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30

Hasil evaluasi model pandas
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.78      0.82         9
           2       0.80      0.89      0.84         9

    accuracy                           0.90        30
   macro avg       0.89      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30



SAVE MODEL

In [24]:
import pickle

with open('model_numpy.pkl', 'wb') as f:
  pickle.dump(pipe_numpy, f)

with open('model_pandas.pkl', 'wb') as model_file:
  pickle.dump(pipe_pandas, model_file)

LOAD MODEL

In [27]:
#Numpy
with open('model_numpy.pkl', 'rb') as model_file:
  loaded_model_numpy = pickle.load(model_file)

#Pandas
with open('model_pandas.pkl', 'rb') as model_file:
  loaded_model_pandas = pickle.load(model_file)

MEMASUKKAN DATA PREDIKSI BARU UNTUK MENCOBA

In [33]:
new_data = [[2,3,4,5]]
loaded_model_numpy.predict(new_data)


array([2])

In [34]:
new_data_df = pd.DataFrame([[1,1,1,1]], columns=iris.feature_names)
loaded_model_pandas.predict(new_data_df)

array([1])